@startuml 4S店基本信息管理
title 4S店基本信息管理

|4S信息管理员|
start
:车型库中选择4S车型信息;
if (库中无?) then (是)
  :增加4S车型信息（excel表）;
endif
|总部信息员|
:审核4S车型信息（更新车型库）;
|4S信息管理员|
:服务类别库中选择;
if (库中无?) then (是)
  :增加服务类别（excel表）;
endif
|总部信息员|
:审核4S服务类别（更新服务类别库）;
|4S信息管理员|
:增修服务时段信息\n（含服务类别及工位数）;
|总部信息员|
:审核4S服务时段信息;
stop
@enduml
