@startuml 卡券管理
title 卡券管理

|总部信息员|
start
:增修卡券类型：服务类别+（次卡、月卡、年卡）\n期限：开始日期、结束日期、有效期长;

|总部系统管理员|
:审核卡券类型;

|4S信息管理员|
:卡券发放（车辆）支持excel批量;
:卡券发放（客户）支持excel批量;
note right
  客户发放支持按车辆查找客户
end note

|4S财务审核|
:卡券发放审核;

|4S业务顾问|
:发起卡券核销申请（服务清单）\n自动建立业务顾问与客户的关联关系;

|4S财务审核|
:卡券核销审核;
stop
@enduml
